[package]
name = "ltypes"
version = "0.1.0"
edition = "2021"

[dependencies]
hex.workspace = true
serde.workspace = true
lcrypto = { path = "../lcrypto" }
serde_bytes = "0.11.15"

[dev-dependencies]
proptest.workspace = true
proptest-derive.workspace = true
rand.workspace = true
